import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Link href="/dashboard">Категории</Link>
          <Link href="/dashboard/albums">Товары</Link>
          <Link href="/dashboard">Новости</Link>
          <Link href="/dashboard/users">Админы</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
