import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Link href="/dashboard">Дешбоард</Link>
          <Link href="/dashboard/albums">Альбомы</Link>
          <Link href="/dashboard/users">Пользователи</Link>
          <Link href="/">На Главную Страницу Сайта</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
